model = 'gpt-5.5'
model_reasoning_effort = 'xhigh'

[mcpServers]
[mcpServers.blender]
args = ['blender-mcp']
command = 'uvx'

[mcp_servers]

[mcp_servers.MCP_DOCKER]
command = "docker.exe"
args = ["mcp", "gateway", "run", "--profile", "biyoconaps"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp", "--api-key", "YOUR_API_KEY"]

[mcp_servers.gce]
url = "https://compute.googleapis.com/mcp"

[mcp_servers.Kastalien-Research-thoughtbox]
url = "https://thoughtbox-prod.fly.dev/mcp"

[mcp_servers.excel]
url = "https://smithery-composio.smithery.workers.dev/excel/mcp"

[mcp_servers.thoughtbox]
command = "npx"
args = ["-y", "@kastalien-research/thoughtbox"]

[mcp_servers.webflow]
url = "https://mcp.webflow.com/mcp"

[mcp_servers.nanobanana]
url = "https://nanobanana.run.tools"

[mcp_servers.todoist]
url = "https://smithery-composio.smithery.workers.dev/todoist/mcp"

[model_providers]
[model_providers.ollama-launch]
base_url = 'http://127.0.0.1:11434/v1/'
name = 'Ollama'

[notice]
[notice.model_migrations]
'gpt-5.2' = 'gpt-5.4'
'gpt-5.3-codex' = 'gpt-5.4'

[preferences]
coworkScheduledTasksEnabled = false
localAgentModeTrustedFolders = ['C:\Users\Biyocon\Documents\GitHub\BKP-V17-main\BKP-V17-main', 'C:\Users\Biyocon\Documents\GitHub\BKP-V17-main']
sidebarMode = 'chat'

[profiles]
[profiles.ollama-launch]
forced_login_method = 'api'
model_provider = 'ollama-launch'
openai_base_url = 'http://127.0.0.1:11434/v1/'

[projects]
[projects.'C:\']
trust_level = 'trusted'

[projects.'C:\BIYOCON-AS\bogfoering']
trust_level = 'trusted'

[projects.'C:\Banedanmark']
trust_level = 'trusted'

[projects.'C:\Banedanmark\00_inbox']
trust_level = 'trusted'

[projects.'C:\Banedanmark\02_banebygenterprise\bkp']
trust_level = 'trusted'

[projects.'C:\Banedanmark\02_banebygenterprise\bkp\BKP-V17-main']
trust_level = 'trusted'

[projects.'C:\Banedanmark\09_Jernbanesikkerhedsorganisation']
trust_level = 'trusted'

[projects.'C:\Games\Europa.Universalis.V.v1.1.9']
trust_level = 'trusted'

[projects.'C:\Games\Football Manager 2023']
trust_level = 'trusted'

[projects.'C:\Liban']
trust_level = 'trusted'

[projects.'C:\Program Files\Autodesk\Autodesk Revit 2026']
trust_level = 'trusted'

[projects.'C:\TASK-MANAGER']
trust_level = 'trusted'

[projects.'C:\TASK-MANAGER\00_Inbox']
trust_level = 'trusted'

[projects.'C:\TASK-MANAGER\00_Inbox\boforing']
trust_level = 'trusted'

[projects.'C:\TASK-MANAGER\00_Inbox\boforing\ApS\2025\Q4']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\CAD']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Documents']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Documents\GitHub']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Documents\GitHub\Cursor4Designers']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Documents\GitHub\NotionMiro']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Documents\GitHub\Perplexica-master']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Documents\GitHub\claw-code-main']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Documents\GitHub\genspark2api-main']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Documents\GitHub\iptv-master']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Documents\GitHub\mirotalksfu-main']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Documents\GitHub\tribev2-main']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Downloads\FIFA_99_Win_RIP_EN\Game Files']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Downloads\my-codespring-project-main']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Hassan-master']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Music']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\OneDrive - Biyocon']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\OneDrive - Biyocon\Desktop\Ahmad']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\OneDrive - Biyocon\Desktop\Håndtilbud']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\OneDrive - Biyocon\Desktop\KAB']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\OneDrive - Biyocon\Desktop\cambuulo-code']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Open source']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Open source\claude-code-main']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Open source\ionic-framework-PWA\ionic-framework-PWA']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Open source\onyx']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Open source\spotube']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Oprydning\Banebyg Kontrakter\UI design af Banebyg Kontrakter']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Spil dev']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Spil dev\eu4-copilot']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Videos']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Videos\BKP v 16 - 17']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Videos\BKP v 16 - 17\Power']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Videos\Paperclip\Ideer\Komplet-Blueprint-Opslagsv-rk']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\Videos\Paperclip\OpenHands-main']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\benchmarks\model-benchmark']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\cambuulo-code']
trust_level = 'trusted'

[projects.'C:\Users\Biyocon\cambuulo-code\OpenMythos-main']
trust_level = 'trusted'

[projects.'C:\Windows\System32']
trust_level = 'trusted'

[projects.'F:\']
trust_level = 'trusted'

[projects.'\\?\C:\Users\Biyocon\Documents\GitHub\Banedanmark']
trust_level = 'trusted'

[projects.'\\?\C:\Users\Biyocon\Documents\GitHub\HMDA']
trust_level = 'trusted'

[projects.'\\?\C:\Users\Biyocon\Documents\GitHub\ToolJet']
trust_level = 'trusted'

[projects.'\\?\C:\Users\Biyocon\Open source\project-bolt']
trust_level = 'trusted'

[projects.'c:\_tooling']
trust_level = 'trusted'

[projects.'c:\_tooling\vscodium']
trust_level = 'trusted'

[projects.'c:\users\biyocon\.antigravity']
trust_level = 'trusted'

[projects.'c:\users\biyocon\.claude\skills']
trust_level = 'trusted'

[projects.'c:\users\biyocon\onedrive - biyocon\desktop\hayat']
trust_level = 'trusted'

[projects.'c:\users\biyocon\onedrive - biyocon\desktop\kvalifikationsordning entreprenør']
trust_level = 'trusted'

[projects.'c:\users\biyocon\onedrive - biyocon\hassan ai']
trust_level = 'trusted'

[projects.'c:\users\biyocon\prompt cloning lab\prompts\clone']
trust_level = 'trusted'

[projects.'c:\users\biyocon\prompt cloning lab\prompts\clone\ide']
trust_level = 'trusted'

[tui]
[tui.model_availability_nux]
'gpt-5.5' = 4

[windows]
sandbox = 'elevated'
