# -*- coding: utf-8 -*-
import os, sys

def write_validation_report():
    lines = [
        "# Fase 14 --- Strukturvalideringsrapport",
        "",
        "**Dato:** 2026-05-06",
        "**Projekt:** Agent Harness --- Kvalifikationsordning Entreprenør",
        "**Valideringsramme:** ADR-0001 (`.vscode/.codex/` som autoritativ runtime) + `.agents/`-specifikation fra blok 3",
        "",
        "---",
        "",
        "## 1. Kritisk konstatering",
        "",
        "Der findes **to parallelle strukturer** i dette projekt:",
        "",
        "| | Autoritativ runtime (ADR-0001) | Embryonisk `.agents/`-struktur |",
        "|---|---|---|",
        "| **Placering** | `.vscode/.codex/` | `.agents/` |",
        "| **Status** | Fuldt fungerende, aktiv i produktion | Tom --- oprettet men aldrig fyldt |",
        "| **Agenter** | 27 roster + 10 Banedanmark placeholders | 0 |",
        "| **Skills** | 73 aktive | 0 |",
        "| **Brain** | 5 filer + ADR | Undermapper uden spec-filer |",
        "| **Scripts** | 3 af 4 PowerShell-scripts | 0 |",
        "",
        "**Konsekvens:** Fase 14's valideringskrav --- designet til at tjekke `.agents/`-strukturen --- kan ikke bestås for den tomme `.agents/`-mappe. Men den EKSTERNE `.vscode/.codex/`-struktur, som ADR-0001 fastslår som autoritativ, består til gengæld næsten alle tjek. Denne rapport dokumenterer begge niveauer.",
        "",
        "---",
        "",
        "## 2. `.agents/`-struktur --- Checkresultater",
        "",
        "| # | Krav | Status | Bemærkning |",
        "|---|---|---|---|",
        "| 1 | `AGENTS.md` i rod | PASS | Findes (1999 bytes). Peger korrekt på `.vscode/.codex/`. |",
        "| 2 | `.agents/registry.yaml` | **FAIL** | `registry.yaml` findes i rod OG i `.vscode/.codex/agents/`, men IKKE under `.agents/`. |",
        "| 3 | `.agents/brain/` med spec-filer | **PARTIAL** | Mappen findes med 4 undermapper. Mangler README.md, context.md, glossary.md, assumptions.md, open-questions.md. |",
        "| 4 | `.agents/agents/` med profile.md+skills.yaml | **FAIL** | Mappen findes men er HELT TOM. Ingen agenter migreret. |",
        "| 5 | `.agents/skills/` med SKILL.md | **FAIL** | Mappen findes men er HELT TOM. Ingen skills migreret. |",
        "| 6 | `.agents/vendor/` med eksterne skills | **FAIL** | Mappen findes men er HELT TOM. |",
        "| 7 | `.agents/scripts/` med 4 PowerShell-scripts | **FAIL** | Mappen findes men er HELT TOM. Ingen scripts migreret. |",
        "| 8 | Avatar-backup | PASS | `Avatar/agents.bak-2026-05-06/` findes med 26 filer. |",
        "| 9 | `.agents/reports/` med Fase 0-3 rapporter | **PARTIAL** | Kun `00_startup_check.md` findes her. Fase 1-3 rapporter ligger i `reports/` (rod-niveau). |",
        "",
        "**Score:** 3 PASS / 2 PARTIAL / 4 FAIL (af 9)",
        "",
        "---",
        "",
        "## 3. Autoritativ runtime --- Checkresultater",
        "",
        "| # | Komponent | Status | Bemærkning |",
        "|---|---|---|---|",
        "| 10 | `registry.yaml` | PASS | Findes i `.vscode/.codex/agents/`. ~37 agenter, 44+ skills, 8+ kategorier. |",
        "| 11 | `agent-roster.json` | PASS | 27 aktive agenter. Ingen orphan-filer. |",
        "| 12 | `agents/banedanmark/` | PASS | 10 placeholder-filer + interface-manager-banebyg.md. |",
        "| 13 | `skills/` | PASS | 73 aktive skills inkl. bdk-*, bbtr-*, bbe-*, karpathy-guidelines, tdd, diagnose. |",
        "| 14 | `prompts/` | PASS | 8 prompts: master-system.md, subagent-builder.md, review-contract.md, vendor-check.md, m.fl. |",
        "| 15 | `Brain/` | PASS | context.md, operating-principles.md, source-map.md, glossary.md, open-questions.md, adr/0001-agent-harness-structure.md |",
        "| 16 | `config.toml` | PASS | Findes. |",
        "| 17 | `Avatar/agents/` | PASS | 38 agentprofiler. Alle i UTF-8. |",
        "| 18 | `README_AGENT_HARNESS.md` | PASS | Beskriver aktiv runtime korrekt. |",
        "| 19 | `.gitignore` | PASS | Dækker Python-build-artefakter. |",
        "| 20 | `scripts/` (rod) | **PARTIAL** | 3 scripts findes. Mangler install-skills.ps1. |",
        "| 21 | `temp/verify_agent_harness.py` | PASS | Findes. |",
        "| 22 | `Kombi/` (reference) | PASS | Iqra-main + mange eksterne repos. |",
        "",
        "**Score:** 10 PASS / 1 PARTIAL / 0 FAIL (af 11)",
        "",
        "---",
        "",
        "## 4. Iqra-integration --- Verifikation",
        "",
        "11/11 Iqra-agenter verificeret med rige system prompts fra Kombi/Iqra-main/.",
        "",
        "---",
        "",
        "## 5. Subagent-mapping til Funktionsbeskrivelser",
        "",
        "`registry.yaml` mapper 10 Banedanmark-subagents til Funktionsbeskrivelser/FB/*.pdf. 217+ PDF'er understotter subagent-kataloget.",
        "",
        "---",
        "",
        "## 6. Valideringskonklusion",
        "",
        "### Passerer",
        "- Autoritativ runtime er fuldt fungerende med 73 skills, 38 agenter, 8 prompts, 5 Brain-filer og komplet ADR-dokumentation.",
        "- Iqra-integration er 100 procent komplet.",
        "- Subagent-mapping er korrekt konfigureret.",
        "- Avatar-system er robust med backup og generation prompts.",
        "",
        "### Fejler",
        "- `.agents/`-strukturen er en tom skal.",
        "- `.agents/registry.yaml` mangler.",
        "- `.agents/agents/`, `.agents/skills/`, `.agents/vendor/`, `.agents/scripts/` er alle tomme.",
        "- `install-skills.ps1` mangler.",
        "",
        "### Arsag til fejl",
        "I blok 3-sessionen blev `.agents/`-mapperne oprettet men aldrig fyldt. ADR-0001 var allerede accepteret, og den autoritative runtime (`.vscode/.codex/`) blev aktivt vedligeholdt. `.agents/`-strukturen blev dermed overflodiggjort.",
        "",
        "### Anbefaling",
        "1. Ryd op: Slet tom `.agents/`-struktur og anerkend `.vscode/.codex/` som eneste autoritativ runtime.",
        "2. Migrer: Kopier alle aktive filer fra `.vscode/.codex/` til `.agents/`.",
        "3. Omdesign: Lad `.agents/` vaere en tynd orchestrator-klient der peger paa `.vscode/.codex/`.",
        "",
        "---",
        "",
        "*Rapport genereret: 2026-05-06 11:40*",
    ]
    with open("reports/validation_report.md", "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("validation_report.md written OK")


def write_final_report():
    lines = [
        "# Fase 15 --- Slutrapport: Agent Harness, Kvalifikationsordning Entreprenor",
        "",
        "**Dato:** 2026-05-06",
        "**Projekt:** Agent Harness (Block 3)",
        "**Status:** Afsluttet med reservationer",
        "",
        "---",
        "",
        "## 1. Opsummering af Kombi/, Avatar/ og Open Source-analyse",
        "",
        "### Kombi/ --- Eksterne kilder",
        "Indhold: 35+ klonede repositories inklusiv Iqra-main (primar kilde til 11 rige agent-systemprompts), agency-agents-main, agentic-stack-master, claude-code-main, deer-flow-main, mattpocock-skills, andrej-karpathy-skills.",
        "Anvendelse: Iqra-main blev aktivt integreret. Andre repos blev klonet som reference.",
        "",
        "### Avatar/ --- Visuel identitet",
        "Indhold: 27 PNG/JPEG avatarer, generation prompt, 38 systemprompt-filer, backup med 26 filer.",
        "Anvendelse: Avatarer er klar til brug. Systemprompts er produktionsklare.",
        "",
        "### Open Source",
        "Projektet er ikke selv open source, men bygger paa: Anthropic Claude Code / Codex CLI, OpenAI GPT-4o / Codex, Iqra framework, mattpocock-skills, andrej-karpathy-skills.",
        "",
        "---",
        "",
        "## 2. Installeret og klonet",
        "",
        "| Komponent | Status | Sti |",
        "|---|---|---|",
        "| Iqra-main | OK Klonet og integreret | Kombi/Iqra-main/ |",
        "| mattpocock-skills | OK Klonet | Kombi/mattpocock-skills-main/ |",
        "| andrej-karpathy-skills | OK Klonet | Kombi/andrej-karpathy-skills-main/ |",
        "| agency-agents | OK Klonet | Kombi/agency-agents-main/ |",
        "| claude-code (reference) | OK Klonet | Kombi/claude-code-main/ |",
        "| Andre 30+ repos | OK Klonet | Kombi/* |",
        "",
        "---",
        "",
        "## 3. Kuraterede skills",
        "",
        "### Inkluderet (73 aktive i .vscode/.codex/skills/)",
        "- BDK/Banedanmark: bdk-roller-kompetencer, bdk-trafikale-regler-anvendelse, bdk-risiko-myndighed, bdk-statens-it-projektmodel-compliance",
        "- BBTR: bbtr-fagpakkestruktur, bbtr-tvaerfaglig-koordinering, bbtr-kvalitet-dod",
        "- BBE: bbe-dokumenter-platform, bbe-ledelsesrapportering",
        "- Generelle: tdd, diagnose, grill-with-docs, setup-matt-pocock-skills, karpathy-guidelines",
        "- Sikkerhed: security-review, vulnerability-scanner",
        "",
        "### Fravalgt",
        "- everything-claude-code-main/ (for omfattende, overlapper)",
        "- caveman-main/, get-shit-done-main/ (ikke professionelt passende)",
        "- 25+ andre (for specialiserede eller generiske)",
        "",
        "---",
        "",
        "## 4. Subagents",
        "",
        "10 Banedanmark-specifikke subagents er defineret i registry.yaml:",
        "- dokumentcontroller (Dokumentation og CM)",
        "- fagansvarlig-spor (Infrastruktur / Spor)",
        "- ibrugtagning (Commissioning)",
        "- kontraktmanager (Kontraktstyring)",
        "- kvalitetsspecialist (Kvalitetssikring)",
        "- miljoekoordinator (Miljo)",
        "- oekonomi-controller (Okonomi)",
        "- planlaegningskoordinator (Planlaegning)",
        "- projekteringsleder (Projektering)",
        "- sikkerhedskoordinator (Sikkerhed)",
        "",
        "Hver subagent har: FB-PDF som autoritativ kilde, mapping i registry.yaml, placeholder-fil i .vscode/.codex/agents/banedanmark/.",
        "",
        "---",
        "",
        "## 5. Avatar-system --- Systemprompts",
        "",
        "38 produktionsklare systemprompts i Avatar/agents/:",
        "- 27 med rige, domaenespecifikke prompts (11 Iqra-agenter)",
        "- 10 med kortere, professionelle prompts (projektroller)",
        "- 1 test-agent",
        "",
        "Kvalitet: Alle UTF-8, YAML-frontmatter paa Banedanmark-profiler, text-fences paa Avatar-prompts.",
        "",
        "---",
        "",
        "## 6. Tilbagevaerende antagelser",
        "",
        "1. .vscode/.codex/ fortsaetter som autoritativ runtime (ADR-0001) --- Lav risiko",
        "2. Kombi/ forbliver som referencekatalog --- Lav risiko",
        "3. FB-PDF'er er korrekte og opdaterede --- Medium risiko",
        "4. registry.yaml er manuelt vedligeholdt --- Medium risiko",
        "5. Avatar-generation prompts kan genbruges --- Lav risiko",
        "6. Codex er primaer model --- Medium risiko",
        "7. OneDrive-reparsepoint er arbejdsdygtigt --- Medium risiko",
        "",
        "---",
        "",
        "## 7. Kendte risici",
        "",
        "| Risiko | Sandsynlighed | Konsekvens | Mitigationsforslag |",
        "|---|---|---|---|",
        "| .agents/ og .vscode/.codex/ divergerer | Hoj | To sandhedskilder | Ryd op eller migrer fuldt |",
        "| registry.yaml og agent-roster.json gaar ud af sync | Medium | Agenter vises forkert | Automatisk sync-script |",
        "| FB-PDF'er foraeldes | Medium | Forkerte kompetencekrav | Halvaarlig revision |",
        "| Kombi/-repos opdateres upstream | Medium | Kloner er foraeldede | git pull --all periodisk |",
        "| Avatar-billeder mangler licens | Lav | Juridisk risiko | Dokumenter kilde |",
        "| OneDrive-sync fejler | Medium | Opdateringer blokeres | Flyt til C:\ (lokal disk) |",
        "| install-skills.ps1 mangler | Medium | Nye skills kan ikke auto-installeres | Skriv scriptet |",
        "",
        "---",
        "",
        "## 8. Test-procedure",
        "",
        "Automatiserede tests:",
        "1. Koer scripts/audit-harness.ps1",
        "2. Koer scripts/validate-harness.ps1",
        "3. Koer scripts/generate-agent-index.ps1",
        "4. Koer python temp/verify_agent_harness.py",
        "",
        "Manuelle tests:",
        "1. Aabn en agent-profil og verificer YAML-frontmatter, text-fence, encoding",
        "2. Aabn registry.yaml og verificer match med agent-roster.json",
        "3. Koer master-system.md som systemprompt i test-session",
        "",
        "Acceptance criteria:",
        "- audit-harness.ps1 rapporterer >= 27 agenter, >= 70 skills, 10 Banedanmark-profiler",
        "- validate-harness.ps1 rapporterer 0 fejl, <= 5 advarsler",
        "- registry.yaml er gyldig YAML",
        "- Alle 11 Iqra-agenter har ikke-tomme systemprompts (> 1000 bytes)",
        "",
        "---",
        "",
        "## 9. Promovering til C:\\Users\\HMDR",
        "",
        "Procedure:",
        "1. Kopier hele projektroden til C:\\Users\\HMDR\\Agent-Harness-Banedanmark\\",
        "2. Sikr at .vscode/.codex/ medfolges",
        "3. Sikr at Avatar/ medfolges",
        "4. Sikr at Funktions- og stillingsbeskrivelser/ medfolges",
        "5. Kombi/ kan ekskluderes for at spare plads",
        "6. Koer scripts/validate-harness.ps1 paa destinationen",
        "7. Opdater AGENTS.md med ny sti hvis nodvendigt",
        "",
        "Obs: ADR-0001 specificerer relative stier, saa promotion boer vaere plug-and-play. Hvis C:\\Users\\HMDR ikke er paa OneDrive, undgaas reparsepoint-problemet.",
        "",
        "---",
        "",
        "## 10. Anbefaling til naeste iteration",
        "",
        "Umiddelbare:",
        "1. Beslut .agents/-skaebne: Ryd op, migrer, eller omdesign",
        "2. Skriv install-skills.ps1",
        "3. Automatisk sync mellem agent-roster.json og registry.yaml",
        "",
        "Kortsigtede:",
        "4. Integrer mattpocock-skills og andrej-karpathy-skills",
        "5. Berig 10 bd-*.md placeholder-filer med FB-indhold",
        "6. Test model-adapters (Kimi, Qwen, Gemini)",
        "",
        "Langsigtede:",
        "7. Overvej GitHub/GitLab-remote for issue-tracking",
        "8. Dokumenter avatar-billeders licens",
        "9. Dockerisering af harness",
        "10. Automatiseret CI/CD med GitHub Actions",
        "",
        "---",
        "",
        "## 11. Sammenfatning",
        "",
        "| Metrik | Resultat |",
        "|---|---|",
        "| Agenter (aktive) | 27 roster + 10 Banedanmark placeholders = 37 total |",
        "| Skills (aktive) | 73 i .vscode/.codex/skills/ |",
        "| Prompts | 8 i .vscode/.codex/prompts/ |",
        "| Brain-filer | 5 + 1 ADR |",
        "| Iqra-integration | 11/11 (100 procent) |",
        "| Avatar-profiler | 38 produktionsklare |",
        "| FB-PDF'er | 217+ |",
        "| PowerShell-scripts | 3/4 (mangler install-skills.ps1) |",
        "| .agents/-struktur | 0 procent (tom skal) |",
        "",
        "Samlet vurdering: Harnessets autoritative runtime (.vscode/.codex/) er produktionsklar og robust. Den planlagte .agents/-struktur er aldrig blevet realiseret. Hvis denne gaeld ryddes op, er harnesset klar til promotion og daglig brug.",
        "",
        "---",
        "",
        "*Rapport genereret: 2026-05-06 11:45*",
    ]
    with open("reports/final_harness_report.md", "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("final_harness_report.md written OK")


if __name__ == "__main__":
    write_validation_report()
    write_final_report()
